/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jav.aatm;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author 91801
 */
public class UserSection extends javax.swing.JFrame {

    /**
     * Creates new form UserSection
     */
    String cardno,sql,pin;
    int flag=0;
    String ph,cid,name;
        long first4;
        int bal;
    public UserSection() {
        initComponents();
    }
    
    public UserSection(String card,String pinno) {
        
        cardno=card;
        pin=pinno;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_back = new javax.swing.JPanel();
        p2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_cl = new javax.swing.JButton();
        text1 = new javax.swing.JTextField();
        btn_ok = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_depo = new javax.swing.JButton();
        btn_withdr = new javax.swing.JButton();
        btn_pchang = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_balance = new javax.swing.JButton();
        btn_state = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        pintxt = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p_back.setBackground(new java.awt.Color(255, 255, 255));

        p2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Amount");

        btn_cl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_cl.setText("Close");
        btn_cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clActionPerformed(evt);
            }
        });

        btn_ok.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_cl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ok)
                    .addComponent(btn_cl))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        btn_depo.setBackground(new java.awt.Color(0, 51, 51));
        btn_depo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_depo.setForeground(new java.awt.Color(204, 204, 204));
        btn_depo.setText("Deposite");
        btn_depo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_depoActionPerformed(evt);
            }
        });

        btn_withdr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_withdr.setText("Withdrawl");
        btn_withdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_withdrActionPerformed(evt);
            }
        });

        btn_pchang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_pchang.setText("Pin change");
        btn_pchang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pchangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_depo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_withdr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_pchang, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btn_depo)
                .addGap(80, 80, 80)
                .addComponent(btn_withdr)
                .addGap(77, 77, 77)
                .addComponent(btn_pchang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        btn_balance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_balance.setText("Balance");
        btn_balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_balanceActionPerformed(evt);
            }
        });

        btn_state.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_state.setText("Mini Statement");
        btn_state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stateActionPerformed(evt);
            }
        });

        btn_close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_state, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
            .addComponent(btn_balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btn_balance)
                .addGap(74, 74, 74)
                .addComponent(btn_state)
                .addGap(77, 77, 77)
                .addComponent(btn_close)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pintxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        label1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout p_backLayout = new javax.swing.GroupLayout(p_back);
        p_back.setLayout(p_backLayout);
        p_backLayout.setHorizontalGroup(
            p_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_backLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(p_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_backLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(p_backLayout.createSequentialGroup()
                        .addGroup(p_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_backLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(pintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_backLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_backLayout.setVerticalGroup(
            p_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_backLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // TODO add your handling code here:
        if (flag==1)
        {
        try
        {
          
          
        p_back.setVisible(true);
           
             
       
            String sql="";
            Class.forName("com.mysql.cj.jdbc.Driver");
        java.sql.Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/atm_new","root","");
       // sql="update cards set balance=balance" +Integer.parseInt(text1.getText())+"where cardno="+cardno ;
        bal=Integer.parseInt(text1.getText());
       
       sql ="update cards set balance=balance+"+bal+" where cardno="+cardno;
         PreparedStatement pst;
        pst = conn.prepareStatement(sql);
        pst.executeUpdate();
         sql="Insert into trans  values(CURDATE(),?,?,?)" ;
         pst = conn.prepareStatement(sql);
         
         
        pst.setString(1,cardno);
        pst.setString(2,"Deposite");
        pst.setInt(3, bal);
      
         pst.executeUpdate();
         sql="select * from cards where cardno="+cardno;
         pst=conn.prepareStatement(sql);
         ResultSet  rs =pst.executeQuery();
        while(rs.next()){
             ph=rs.getString("phone");
         }
         dsms();
        JOptionPane.showMessageDialog(null,"Update Success");
        conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        }
        if (flag==2)
        {
        try
        {
          
          
        p_back.setVisible(true);
            String sql="";
            Class.forName("com.mysql.cj.jdbc.Driver");
        java.sql.Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/atm_new","root","");
       // sql="update cards set balance=balance" +Integer.parseInt(text1.getText())+"where cardno="+cardno ;
         bal=Integer.parseInt(text1.getText());
       
       sql ="update cards set balance=balance-"+bal+" where cardno="+cardno;
         PreparedStatement pst;
        pst = conn.prepareStatement(sql);
        pst.executeUpdate();
        sql="Insert into trans  values(CURDATE(),?,?,?)" ;
         pst = conn.prepareStatement(sql);
         
         
        pst.setString(1,cardno);
        pst.setString(2,"Withdrawl");
        pst.setInt(3, bal);
        pst.executeUpdate();
         sql="select * from cards where cardno="+cardno;
         pst=conn.prepareStatement(sql);
         ResultSet  rs =pst.executeQuery();
        while(rs.next()){
             ph=rs.getString("phone");
         }
         wsms();
        JOptionPane.showMessageDialog(null,"Update Success");
        conn.close();
        }
        catch(Exception e)
        {
            
        }
        }
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_depoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_depoActionPerformed
        // TODO add your handling code here:
        p_back.setVisible(true);
        text1.setText("");
        flag=1;
    }//GEN-LAST:event_btn_depoActionPerformed

    private void btn_withdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_withdrActionPerformed
        // TODO add your handling code here:
         p_back.setVisible(true);
        text1.setText("");
        flag=2;
    }//GEN-LAST:event_btn_withdrActionPerformed

    private void btn_pchangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pchangActionPerformed
        // TODO add your handling code here:
        try{
        String sql="";
        
        Random ran = new Random();
            Class.forName("com.mysql.cj.jdbc.Driver");
        java.sql.Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/atm_new","root","");
        sql="select * from cards where cardno="+cardno;
        PreparedStatement pst;
        pst=conn.prepareStatement(sql);
        long first3 = (ran.nextLong() % 9000L) + 1000L;
        first4 = Math.abs(first3);
      ResultSet  rs =pst.executeQuery();
        while(rs.next()){
             ph=rs.getString("phone");
              cid=rs.getString("cid");
              name=rs.getString("cname");
         }
        sendsms();
        sql ="update cards set pin="+first4+" where cardno="+cardno;
         
        pst = conn.prepareStatement(sql);
        pst.executeUpdate();
      conn.close();
        
        }
        catch(Exception e){}
        
    }//GEN-LAST:event_btn_pchangActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        p_back.setVisible(false);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_balanceActionPerformed
        // TODO add your handling code here:
        try{
            p_back.setVisible(true);
            String bal="";
            Class.forName("com.mysql.cj.jdbc.Driver");
        java.sql.Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/atm_new","root","");
         String  sql="Select balance from cards where cardno=?" ;
     //   pst = conn.prepareStatement(sql);
         PreparedStatement pst;
        pst = conn.prepareStatement(sql);
        pst.setString(1,cardno);
        ResultSet  rs =pst.executeQuery();
        while(rs.next()){
             bal=rs.getString("balance");
                       
         }
        text1.setText(bal);
        conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e); 
        }
    }//GEN-LAST:event_btn_balanceActionPerformed

    private void btn_stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stateActionPerformed
        // TODO add your handling code here:
        try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        java.sql.Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/atm_new","root","");
        sql="select * from trans  where cardno="+cardno + " order by tdate desc limit 5";
        String sql1="\n";
        PreparedStatement pst;
        pst=conn.prepareStatement(sql);
        
      ResultSet  rs =pst.executeQuery();
        while(rs.next()){
             sql1=sql1+rs.getDate("tdate")+"  ";
              sql1=sql1+rs.getString("cardno")+"  ";
              sql1=sql1+rs.getString("type")+"  ";
              sql1=sql1+rs.getInt("amt");
              sql1=sql1+"\n";
         }
        JOptionPane.showMessageDialog(null,sql1);
        
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,e); 
       }
    }//GEN-LAST:event_btn_stateActionPerformed

    private void btn_clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clActionPerformed
        // TODO add your handling code here:
        MainMenu main = new MainMenu();
           main.setVisible(true);
           setVisible(false);
    }//GEN-LAST:event_btn_clActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        // TODO add your handling code here:
        label1.setText(cardno);
        pintxt.setText(pin);
        p_back.setVisible(false);
    }                              
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSection().setVisible(true);
            }
        });
    }
    
    private void sendsms(){
        try{
            String msg="Cust ID:"+cid + "\n Cust Name: " +name +"\n Card Number: " + cardno + "\n Pin:"+ first4 ;
      String apiKey = "apikey=" + "E5NkEd1iDcU-sDlnrtNjzZfZG4XEliiv7C4PerZRTO";
			String message = "&message=" + msg;
			String sender = "&sender=" + "TXTLCL";
			String numbers = "&numbers=" + ph;
			
			// Send data
			HttpURLConnection conn = (HttpURLConnection) new URL("https://api.textlocal.in/send/?").openConnection();
			String data = apiKey + numbers + message + sender;
			conn.setDoOutput(true);
			conn.setRequestMethod("POST");
			conn.setRequestProperty("Content-Length", Integer.toString(data.length()));
			conn.getOutputStream().write(data.getBytes("UTF-8"));
			final BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
			final StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = rd.readLine()) != null) {
				//stringBuffer.append(line);
                                JOptionPane.showMessageDialog(null,"Sms Sent");
			}
			rd.close();
			
    }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null,"Sms Not Sent ");
        }
    }
private void wsms(){
        try{
            String msg="\n Card Number: " + cardno + "\n Withdrawl Amount:"+ bal ;
      String apiKey = "apikey=" + "E5NkEd1iDcU-sDlnrtNjzZfZG4XEliiv7C4PerZRTO";
			String message = "&message=" + msg;
			String sender = "&sender=" + "TXTLCL";
			String numbers = "&numbers=" + ph;
			
			// Send data
			HttpURLConnection conn = (HttpURLConnection) new URL("https://api.textlocal.in/send/?").openConnection();
			String data = apiKey + numbers + message + sender;
			conn.setDoOutput(true);
			conn.setRequestMethod("POST");
			conn.setRequestProperty("Content-Length", Integer.toString(data.length()));
			conn.getOutputStream().write(data.getBytes("UTF-8"));
			final BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
			final StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = rd.readLine()) != null) {
				//stringBuffer.append(line);
                                JOptionPane.showMessageDialog(null,"Sms Sent");
			}
			rd.close();
			
    }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null,"Sms Not Sent ");
        }
    }
private void dsms(){
        try{
            String msg="\n Card Number: " + cardno + "\n Deposited Amount:"+ bal ;
      String apiKey = "apikey=" + "E5NkEd1iDcU-sDlnrtNjzZfZG4XEliiv7C4PerZRTO";
			String message = "&message=" + msg;
			String sender = "&sender=" + "TXTLCL";
			String numbers = "&numbers=" + ph;
			
			// Send data
			HttpURLConnection conn = (HttpURLConnection) new URL("https://api.textlocal.in/send/?").openConnection();
			String data = apiKey + numbers + message + sender;
			conn.setDoOutput(true);
			conn.setRequestMethod("POST");
			conn.setRequestProperty("Content-Length", Integer.toString(data.length()));
			conn.getOutputStream().write(data.getBytes("UTF-8"));
			final BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
			final StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = rd.readLine()) != null) {
				//stringBuffer.append(line);
                                JOptionPane.showMessageDialog(null,"Sms Sent");
			}
			rd.close();
			
    }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null,"Sms Not Sent ");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_balance;
    private javax.swing.JButton btn_cl;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_depo;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_pchang;
    private javax.swing.JButton btn_state;
    private javax.swing.JButton btn_withdr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p_back;
    private javax.swing.JLabel pintxt;
    private javax.swing.JTextField text1;
    // End of variables declaration//GEN-END:variables
}
